parameters:
  - name: env
    type: string

steps:
  - script: |
      bicep build-params deploy/params/main.${{ parameters.env }}.bicepparam
    name: BuildParams_${{ parameters.env }}
    displayName: Build ${{ parameters.env }} Params